name: DEPLOY TO STAGING

on:
  push:
    branches:
      - gh-pages

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing project dependencies
        run: npm install

      - name: Building the project
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}