name: Build and Deploy Vue App

on:
  push:
    branches:
      - master  # Замените на имя вашей основной ветки, если оно отличается

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'Mak0n1'
          reponame: 'PanaceaFront'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
